---
type: showroom
view_switcher:
  enabled: true
  default_mode: split
persist_url_state: true
tabs:
  - name: Terminal
    path: /terminal
    port: 443
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: OpenShift AI Dashboard
    url: 'https://rhods-dashboard-redhat-ods-applications.${DOMAIN}'
